/*-------- DATA FOR SMOELENBOEK --------*/
USE `smoelenboek`;

/*------- User Variables -------*/
SET @DEFAULT_PASSWORD = 'qwerty';
SET @DEFAULT_IMAGE = 'default.jpg';

/*---- DATA FOR KLASSEN ----*/
-- INSERT INTO `klassen`
-- (`naam`, `mentor_id`)
-- VALUES
-- ('1A', NULL),
-- ('1B', NULL),
-- ('2A', NULL),
-- ('2B', NULL),
-- ('3A', NULL),
-- ('3B', NULL);

INSERT INTO `klassen` 
(`naam`, `mentor_id`)
VALUES
('IF-AO4-1H', null),
('IF-AO4-1J', null),
('IF-AO4-1K', null),
('IF-AO4-2H', null),
('IF-AO4-2J', null),
('IF-AO4-3H', null),
('IF-AO4-3J', null),
('IF-AO4-3S-PK', null),
('IF-AO4-4H', null),
('IF-AO4-4S', null),
('IF-AO4-4S-PK', null);

/*---- DATA FOR KLASSEN ----*/
INSERT INTO `personen` 
(`id`, `vnaam`, `tv`, `anaam`, `gebrnaam`, `ww`, `email`, `telnummer`, `foto`, `opmerkingen`, `adres`, `plaats`, `klas_id`, `recht`) 
VALUES
(1, 'Ivan', 'Ivanov', 'Peev', 'ipeev', 'qwerty', 'i.ivanov.peev@mondriaanict.nl', '31612345678', 'img/personen/ipeev.png', 'asdasd', NULL, NULL, 6, 'leerling'),
(2, 'Bo', NULL, 'Alsemgeest', 'balsemgeest', 'qwerty', 'b.alsemgeest@mondriaanict.nl', '31612345678', 'img/personen/balsemgeest.png', NULL, NULL, NULL, 1, 'leerling'),
(3, 'Jashwand', NULL, 'Autar', 'jautar', 'qwerty', 'j.autar@mondriaanict.nl', '31612345678', 'img/personen/jautar.png', NULL, NULL, NULL, 1, 'leerling'),
(4, 'Jay', NULL, 'Badal', 'jbadal', 'qwerty', 'j.badal@mondriaanict.nl', '31612345678', 'img/personen/jbadal.png', NULL, NULL, NULL, 1, 'leerling'),
(5, 'Gawain', NULL, 'Beunk', 'gbeunk', 'qwerty', 'g.beunk@mondriaanict.nl', '31612345678', 'img/personen/gbeunk.png', NULL, NULL, NULL, 1, 'leerling'),
(6, 'Tian', NULL, 'Cheng', 'tcheng', 'qwerty', 't.cheng@mondriaanict.nl', '31612345678', 'img/personen/tcheng.png', NULL, NULL, NULL, 1, 'leerling'),
(7, 'Sven', 'van', 'Elswijk', 'selswijk', 'qwerty', 's.van.elswijk@mondriaanict.nl', '31612345678', 'img/personen/selswijk.png', NULL, NULL, NULL, 1, 'leerling'),
(8, 'Laurens', NULL, 'Eman', 'leman', 'qwerty', 'l.eman@mondriaanict.nl', '31612345678', 'img/personen/leman.png', NULL, NULL, NULL, 1, 'leerling'),
(9, 'Kevin', NULL, 'Fiolet', 'kfiolet', 'qwerty', 'k.fiolet@mondriaanict.nl', '31612345678', 'img/personen/kfiolet.png', NULL, NULL, NULL, 1, 'leerling'),
(10, 'Stijn', NULL, 'Hoogenboom', 'shoogenboom', 'qwerty', 's.hoogenboom@mondriaanict.nl', '31612345678', 'img/personen/shoogenboom.png', NULL, NULL, NULL, 1, 'leerling'),
(11, 'Thaha', NULL, 'Jemni', 'tjemni', 'qwerty', 't.jemni@mondriaanict.nl', '31612345678', 'img/personen/tjemni.png', NULL, NULL, NULL, 1, 'leerling'),
(12, 'Brian', NULL, 'Koopman', 'bkoopman', 'qwerty', 'b.koopman@mondriaanict.nl', '31612345678', 'img/personen/bkoopman.png', NULL, NULL, NULL, 1, 'leerling'),
(13, 'Daan', NULL, 'Kort', 'dkort', 'qwerty', 'd.kort@mondriaanict.nl', '31612345678', 'img/personen/dkort.png', NULL, NULL, NULL, 1, 'leerling'),
(14, 'Hasan', NULL, 'Kosedag', 'hkosedag', 'qwerty', 'h.kosedag@mondriaanict.nl', '31612345678', 'img/personen/default.png', NULL, NULL, NULL, 1, 'leerling'),
(15, 'Leon', 'van der', 'Noll', 'lnoll', 'qwerty', 'l.van.der.noll@mondriaanict.nl', '31612345678', 'img/personen/lnoll.png', NULL, NULL, NULL, 1, 'leerling'),
(16, 'Anwar', NULL, 'Oemar', 'aoemar', 'qwerty', 'a.oemar@mondriaanict.nl', '31612345678', 'img/personen/aoemar.png', NULL, NULL, NULL, 1, 'leerling'),
(17, 'Miran', NULL, 'Raza', 'mraza', 'qwerty', 'm.raza@mondriaanict.nl', '31612345678', 'img/personen/default.png', NULL, NULL, NULL, 1, 'leerling'),
(18, 'Vijay', NULL, 'Sankar', 'vsankar', 'qwerty', 'v.sankar@mondriaanict.nl', '31612345678', 'img/personen/vsankar.png', NULL, NULL, NULL, 1, 'leerling'),
(19, 'Quincy', NULL, 'Schelkers', 'qschelkers', 'qwerty', 'q.schelkers@mondriaanict.nl', '31612345678', 'img/personen/qschelkers.png', NULL, NULL, NULL, 1, 'leerling'),
(20, 'Dwayne', NULL, 'Spinnler', 'dspinnler', 'qwerty', 'd.spinnler@mondriaanict.nl', '31612345678', 'img/personen/dspinnler.png', NULL, NULL, NULL, 1, 'leerling'),
(21, 'Maarten', NULL, 'Treure', 'mtreure', 'qwerty', 'm.treure@mondriaanict.nl', '31612345678', 'img/personen/mtreure.png', NULL, NULL, NULL, 1, 'leerling'),
(22, 'Verhoorn', NULL, 'Lars', 'lverhoorn', 'qwerty', 'l.verhoorn@mondriaanict.nl', '31612345678', 'img/personen/lverhoorn.png', NULL, NULL, NULL, 1, 'leerling'),
(23, 'Danny', 'van der', 'Wel', 'dwel', 'qwerty', 'd.van.der.wel@mondriaanict.nl', '31612345678', 'img/personen/dwel.png', NULL, NULL, NULL, 1, 'leerling'),
(24, 'Daan', 'de', 'Wit', 'dwit', 'qwerty', 'd.de.wit@mondriaanict.nl', '31612345678', 'img/personen/dwit.png', NULL, NULL, NULL, 1, 'leerling'),
(25, 'Ariano', NULL, 'Wongsosetro', 'awongsosetro', 'qwerty', 'a.wongsosetro@mondriaanict.nl', '31612345678', 'img/personen/awongsosetro.png', NULL, NULL, NULL, 1, 'leerling'),
(26, 'Matthew', NULL, 'Arkenbout', 'markenbout', 'qwerty', 'm.arkenbout@mondriaanict.nl', '31612345678', 'img/personen/markenbout.png', NULL, NULL, NULL, 2, 'leerling'),
(27, 'Mehmet', NULL, 'Balci', 'mbalci', 'qwerty', 'm.balci@mondriaanict.nl', '31612345678', 'img/personen/mbalci.png', NULL, NULL, NULL, 2, 'leerling'),
(28, 'Edelmar', NULL, 'Balyn', 'ebalyn', 'qwerty', 'e.balyn@mondriaanict.nl', '31612345678', 'img/personen/ebalyn.png', NULL, NULL, NULL, 2, 'leerling'),
(29, 'Gürkan', NULL, 'Basak', 'gbasak', 'qwerty', 'g.basak@mondriaanict.nl', '31612345678', 'img/personen/gbasak.png', NULL, NULL, NULL, 2, 'leerling'),
(30, 'Yoshua', NULL, 'Bosman', 'ybosman', 'qwerty', 'y.bosman@mondriaanict.nl', '31612345678', 'img/personen/ybosman.png', NULL, NULL, NULL, 2, 'leerling'),
(31, 'Mika', 'van den', 'Broek', 'mbroek', 'qwerty', 'm.van.der.broek@mondriaanict.nl', '31612345678', 'img/personen/mbroek.png', NULL, NULL, NULL, 2, 'leerling'),
(32, 'Ozan', NULL, 'Celebi', 'ocelebi', 'qwerty', 'o.celebi@mondriaanict.nl', '31612345678', 'img/personen/ocelebi.png', NULL, NULL, NULL, 2, 'leerling'),
(33, 'Wasiem', NULL, 'El-Idrioui', 'welidrioui', 'qwerty', 'w.elidrioui@mondriaanict.nl', '31612345678', 'img/personen/welidrioui.png', NULL, NULL, NULL, 2, 'leerling'),
(34, 'Delano', NULL, 'Francisco', 'dfrancisco', 'qwerty', 'd.francisco@mondriaanict.nl', '31612345678', 'img/personen/dfrancisco.png', NULL, NULL, NULL, 2, 'leerling'),
(35, 'Jordy', NULL, 'Groen', 'jgroen', 'qwerty', 'j.groen@mondriaanict.nl', '31612345678', 'img/personen/jgroen.png', NULL, NULL, NULL, 2, 'leerling'),
(36, 'Kimberly', NULL, 'Guth', 'kguth', 'qwerty', 'k.guth@mondriaanict.nl', '31612345678', 'img/personen/kguth.png', NULL, NULL, NULL, 2, 'leerling'),
(37, 'Richard', NULL, 'Hausil', 'rhausil', 'qwerty', 'r.hausil@mondriaanict.nl', '31612345678', 'img/personen/rhausil.png', NULL, NULL, NULL, 2, 'leerling'),
(38, 'Timo', NULL, 'Jansen', 'tjansen', 'qwerty', 't.jansen@mondriaanict.nl', '31612345678', 'img/personen/tjansen.png', NULL, NULL, NULL, 2, 'leerling'),
(39, 'Ryan', NULL, 'Kroon', 'rkroon', 'qwerty', 'r.kroon@mondriaanict.nl', '31612345678', 'img/personen/rkroon.png', NULL, NULL, NULL, 2, 'leerling'),
(40, 'Danny', NULL, 'Kropff', 'dkropff', 'qwerty', 'd.kropff@mondriaanict.nl', '31612345678', 'img/personen/dkropff.png', NULL, NULL, NULL, 2, 'leerling'),
(41, 'Ajob', NULL, 'Kustra', 'akustra', 'qwerty', 'a.kustra@mondriaanict.nl', '31612345678', 'img/personen/akustra.png', NULL, NULL, NULL, 2, 'leerling'),
(42, 'Timon', NULL, 'Landmeter', 'tlandmeter', 'qwerty', 't.landmeter@mondriaanict.nl', '31612345678', 'img/personen/tlandmeter.png', NULL, NULL, NULL, 2, 'leerling'),
(43, 'Jainash', NULL, 'Mohan', 'jmohan', 'qwerty', 'j.mohan@mondriaanict.nl', '31612345678', 'img/personen/jmohan.png', NULL, NULL, NULL, 2, 'leerling'),
(44, 'Remi', NULL, 'Reijnhoudt', 'rreijnhout', 'qwerty', 'r.reijnhout@mondriaanict.nl', '31612345678', 'img/personen/rreijnhout.png', NULL, NULL, NULL, 2, 'leerling'),
(45, 'Youri', 'van', 'Rutten', 'yrutten', 'qwerty', 'y.rutten@mondriaanict.nl', '31612345678', 'img/personen/yrutten.png', NULL, NULL, NULL, 2, 'leerling'),
(46, 'Sander', NULL, 'Scheenstra', 'sscheenstra', 'qwerty', 's.scheenstra@mondriaanict.nl', '31612345678', 'img/personen/sscheenstra.png', NULL, NULL, NULL, 2, 'leerling'),
(47, 'Raoul', NULL, 'Soerdjbalie', 'rsoerdjbalie', 'qwerty', 'r.soerdjbalie@mondriaanict.nl', '31612345678', 'img/personen/rsoerdjbalie.png', NULL, NULL, NULL, 2, 'leerling'),
(48, 'Mike', NULL, 'Vonk', 'mvonk', 'qwerty', 'm.vonk@mondriaanict.nl', '31612345678', 'img/personen/mvonk.png', NULL, NULL, NULL, 2, 'leerling'),
(49, 'Bilal', NULL, 'Zambib', 'bzambib', 'qwerty', 'b.zambib@mondriaanict.nl', '31612345678', 'img/personen/bzambib.png', NULL, NULL, NULL, 2, 'leerling'),
(50, 'Toby', NULL, 'Benschop', 'tbenschop', 'qwerty', 't.benschop@mondriaanict.nl', '31612345678', 'img/personen/tbenschop.png', NULL, NULL, NULL, 3, 'leerling'),
(51, 'Don', NULL, 'Besic', 'dbesic', 'qwerty', 'd.besic@mondriaanict.nl', '31612345678', 'img/personen/dbesic.png', NULL, NULL, NULL, 3, 'leerling'),
(52, 'Tim', NULL, 'Booden', 'tbooden', 'qwerty', 't.booden@mondriaanict.nl', '31612345678', 'img/personen/tbooden.png', NULL, NULL, NULL, 3, 'leerling'),
(53, 'Yareck', NULL, 'Budwilowitz', 'ybudwilowitz', 'qwerty', 'y.budwilowitz@mondriaanict.nl', '31612345678', 'img/personen/ybudwilowitz.png', NULL, NULL, NULL, 3, 'leerling'),
(54, 'Akash', NULL, 'Datadin', 'adatadin', 'qwerty', 'a.datadin@mondriaanict.nl', '31612345678', 'img/personen/adatadin.png', NULL, NULL, NULL, 3, 'leerling'),
(55, 'Mohammed', NULL, 'Douairi', 'mdouairi', 'qwerty', 'm.douairi@mondriaanict.nl', '31612345678', 'img/personen/mdouairi.png', NULL, NULL, NULL, 3, 'leerling'),
(56, 'Hamid', NULL, 'El Asmy', 'helasmy', 'qwerty', 'h.elasmy@mondriaanict.nl', '31612345678', 'img/personen/helasmy.png', NULL, NULL, NULL, 3, 'leerling'),
(57, 'Koen', 'van der', 'Els', 'kels', 'qwerty', 'k.van.der.els@mondriaanict.nl', '31612345678', 'img/personen/kels.png', NULL, NULL, NULL, 3, 'leerling'),
(58, 'Gio', NULL, 'Groeneveld', 'ggroeneveld', 'qwerty', 'g.groeneveld@mondriaanict.nl', '31612345678', 'img/personen/ggroeneveld.png', NULL, NULL, NULL, 3, 'leerling'),
(59, 'Aisha', NULL, 'Khelawan', 'akhelawan', 'qwerty', 'a.khelawan@mondriaanict.nl', '31612345678', 'img/personen/akhelawan.png', NULL, NULL, NULL, 3, 'leerling'),
(60, 'Harman', NULL, 'Kocer', 'hkocer', 'qwerty', 'h.kocer@mondriaanict.nl', '31612345678', 'img/personen/hkocer.png', NULL, NULL, NULL, 3, 'leerling'),
(61, 'Wessel', 'van', 'Leeuwen', 'wleeuwen', 'qwerty', 'w.leeuwen@mondriaanict.nl', '31612345678', 'img/personen/wleeuwen.png', NULL, NULL, NULL, 3, 'leerling'),
(62, 'Suraj', NULL, 'Lila', 'slila', 'qwerty', 's.lila@mondriaanict.nl', '31612345678', 'img/personen/slila.png', NULL, NULL, NULL, 3, 'leerling'),
(63, 'Haiwen', NULL, 'Ma', 'hma', 'qwerty', 'h.ma@mondriaanict.nl', '31612345678', 'img/personen/hma.png', NULL, NULL, NULL, 3, 'leerling'),
(64, 'Xhander', NULL, 'Marchena', 'xmarchena', 'qwerty', 'x.marchena@mondriaanict.nl', '31612345678', 'img/personen/xmarchena.png', NULL, NULL, NULL, 3, 'leerling'),
(65, 'Dyon', 'van der', 'Meer', 'dmeer', 'qwerty', 'd.van.der.meer@mondriaanict.nl', '31612345678', 'img/personen/dmeer.png', NULL, NULL, NULL, 3, 'leerling'),
(66, 'Ismael', NULL, 'Ouled L\Kadi', 'iouledlkadi', 'qwerty', 'i.ouledlkadi@mondriaanict.nl', '31612345678', 'img/personen/iouledlkadi.png', NULL, NULL, NULL, 3, 'leerling'),
(67, 'Michael', 'van', 'Praet', 'mpraet', 'qwerty', 'm.van.praet@mondriaanict.nl', '31612345678', 'img/personen/mpraet.png', NULL, NULL, NULL, 3, 'leerling'),
(68, 'Roy', NULL, 'Roodenburg', 'rroodenburg', 'qwerty', 'r.roodenburg@mondriaanict.nl', '31612345678', 'img/personen/rroodenburg.png', NULL, NULL, NULL, 3, 'leerling'),
(69, 'Mike', NULL, 'Santifort', 'msantifort', 'qwerty', 'm.santifort@mondriaanict.nl', '31612345678', 'img/personen/msantifort.png', NULL, NULL, NULL, 3, 'leerling'),
(70, 'Bashiru', NULL, 'Sesay', 'bsesay', 'qwerty', 'b.sesay@mondriaanict.nl', '31612345678', 'img/personen/bsesay.png', NULL, NULL, NULL, 3, 'leerling'),
(71, 'Walter', NULL, 'Simons', 'wsimons', 'qwerty', 'w.simons@mondriaanict.nl', '31612345678', 'img/personen/wsimons.png', NULL, NULL, NULL, 3, 'leerling'),
(72, 'Bram', NULL, 'Verburg', 'bverburg', 'qwerty', 'b.verburg@mondriaanict.nl', '31612345678', 'img/personen/bverburg.png', NULL, NULL, NULL, 3, 'leerling'),
(73, 'Jeffrey', NULL, 'Verhoef', 'jverhoef', 'qwerty', 'j.verhoef@mondriaanict.nl', '31612345678', 'img/personen/jverhoef.png', NULL, NULL, NULL, 3, 'leerling'),
(74, 'Luna', NULL, 'Willems', 'lwillems', 'qwerty', 'l.willems@mondriaanict.nl', '31612345678', 'img/personen/lwillems.png', NULL, NULL, NULL, 3, 'leerling'),
(75, 'Mike', 'de', 'Bakker', 'mbakker', 'cxz', 'm.bakker@mondriaanict.nl', '31612345678', 'img/personen/mbakker.png', 'adszxcxcv', NULL, NULL, 4, 'leerling'),
(76, 'Sofyan', 'el', 'Barzouhi', 'sbarzouhi', 'qwerty', 's.barzouhi@mondriaanict.nl', '31612345678', 'img/personen/sbarzouhi.png', '', NULL, NULL, 4, 'leerling'),
(77, 'Floris', NULL, 'Boers', 'fboers', 'qwerty', 'f.boers@mondriaanict.nl', '31612345678', 'img/personen/fboers.png', NULL, NULL, NULL, 4, 'leerling'),
(78, 'Mike', 'de', 'Bolster', 'mbolster', 'qwerty', 'm.bolster@mondriaanict.nl', '31612345678', 'img/personen/mbolster.png', NULL, NULL, NULL, 4, 'leerling'),
(79, 'Peter', NULL, 'Born', 'pborn', 'qwerty', 'p.born@mondriaanict.nl', '31612345678', 'img/personen/pborn.png', NULL, NULL, NULL, 4, 'leerling'),
(80, 'Wesley', NULL, 'Gahr', 'wgahr', 'qwerty', 'w.gahr@mondriaanict.nl', '31612345678', 'img/personen/wgahr.png', 'zxczxcxzc', NULL, NULL, 4, 'leerling'),
(81, 'Joran', NULL, 'Kant', 'jkant', 'qwerty', 'j.kant@mondriaanict.nl', '31612345678', 'img/personen/jkant.png', NULL, NULL, NULL, 4, 'leerling'),
(82, 'Menno', NULL, 'Koppe', 'mkoppe', 'qwerty', 'm.koppe@mondriaanict.nl', '31612345678', 'img/personen/mkoppe.png', NULL, NULL, NULL, 4, 'leerling'),
(83, 'Koen', NULL, 'Kort', 'kkort', 'qwerty', 'k.kort@mondriaanict.nl', '31612345678', 'img/personen/kkort.png', 'zxcv', NULL, NULL, 4, 'leerling'),
(84, 'Yunus', 'Emre', 'Kurtal', 'ykurtal', 'qwerty', 'y.emre.kurtal@mondriaanict.nl', '31612345678', 'img/personen/ykurtal.png', NULL, NULL, NULL, 4, 'leerling'),
(85, 'Yuri', NULL, 'Lamijo', 'ylamijo', 'qwerty', 'y.lamijo@mondriaanict.nl', '31612345678', 'img/personen/ylamijo.png', NULL, NULL, NULL, 4, 'leerling'),
(86, 'Chris', NULL, 'Meurink', 'cmeurink', 'qwerty', 'c.meurink@mondriaanict.nl', '31612345678', 'img/personen/cmeurink.png', NULL, NULL, NULL, 4, 'leerling'),
(87, 'Kylian', NULL, 'Nieuwmans', 'knieuwmans', 'qwerty', 'k.nieuwmans@mondriaanict.nl', '31612345678', 'img/personen/knieuwmans.png', NULL, NULL, NULL, 4, 'leerling'),
(88, 'Marko', NULL, 'Nikolic', 'mnikolic', 'qwerty', 'm.nikolic@mondriaanict.nl', '31612345678', 'img/personen/mnikolic.png', NULL, NULL, NULL, 4, 'leerling'),
(89, 'Hugo', 'van', 'Schie', 'hschie', 'qwerty', 'h.van.schie@mondriaanict.nl', '31612345678', 'img/personen/hschie.png', NULL, NULL, NULL, 4, 'leerling'),
(90, 'Sem', 'van der', 'Schilt', 'sschilt', 'qwerty', 's.van.der.schilt@mondriaanict.nl', '31612345678', 'img/personen/sschilt.png', NULL, NULL, NULL, 4, 'leerling'),
(91, 'Shaquile', NULL, 'Sewbaransingh', 'ssewbaransingh', 'qwerty', 's.sewbaransingh@mondriaanict.nl', '31612345678', 'img/personen/ssewbaransingh.png', NULL, NULL, NULL, 4, 'leerling'),
(92, 'Darren', NULL, 'Siriram', 'dsiriram', 'qwerty', 'd.siriram@mondriaanict.nl', '31612345678', 'img/personen/dsiriram.png', NULL, NULL, NULL, 4, 'leerling'),
(93, 'Falco', NULL, 'Strijk', 'fstrijk', 'qwerty', 'f.strijk@mondriaanict.nl', '31612345678', 'img/personen/fstrijk.png', NULL, NULL, NULL, 4, 'leerling'),
(94, 'Darren', NULL, 'Tan', 'dtan', 'qwerty', 'd.tan@mondriaanict.nl', '31612345678', 'img/personen/dtan.png', NULL, NULL, NULL, 4, 'leerling'),
(95, 'Nick', NULL, 'Visser', 'nvisser', 'qwerty', 'n.visser@mondriaanict.nl', '31612345678', 'img/personen/nvisser.png', NULL, NULL, NULL, 4, 'leerling'),
(96, 'Jordy', NULL, 'Voorham', 'jvoorham', 'qwerty', 'j.voorham@mondriaanict.nl', '31612345678', 'img/personen/jvoorham.png', NULL, NULL, NULL, 4, 'leerling'),
(97, 'Mikolaj', NULL, 'Wichrowski', 'mwichrowski', 'qwerty', 'm.wichrowski@mondriaanict.nl', '31612345678', 'img/personen/mwichrowski.png', NULL, NULL, NULL, 4, 'leerling'),
(98, 'Bertus', NULL, 'Wisman', 'bwisman', 'qwerty', 'b.wisman@mondriaanict.nl', '31612345678', 'img/personen/bwisman.png', NULL, NULL, NULL, 4, 'leerling'),
(99, 'Ajeeth', NULL, 'Adaikkalanuthu', 'aadaikkalanuthu', 'qwerty', 'a.adaikkalanuthu@mondriaanict.nl', '31612345678', 'img/personen/aadaikkalanuthu.png', NULL, NULL, NULL, 5, 'leerling'),
(100, 'Sayfedine', NULL, 'Amajoud', 'samajoud', 'qwerty', 's.amajoud@mondriaanict.nl', '31612345678', 'img/personen/samajoud.png', NULL, NULL, NULL, 5, 'leerling'),
(101, 'Bas', NULL, 'Boosman', 'bboosman', 'qwerty', 'b.boosman@mondriaanict.nl', '31612345678', 'img/personen/bboosman.png', NULL, NULL, NULL, 5, 'leerling'),
(102, 'Timo', NULL, 'Botter', 'tbotter', 'qwerty', 't.botter@mondriaanict.nl', '31612345678', 'img/personen/tbotter.png', NULL, NULL, NULL, 5, 'leerling'),
(103, 'Tristan', NULL, 'Dalmeijer', 'tdalmeijer', 'qwerty', 't.dalmeijer@mondriaanict.nl', '31612345678', 'img/personen/tdalmeijer.png', NULL, NULL, NULL, 5, 'leerling'),
(104, 'Kishan', NULL, 'Debi Tewari', 'kdebitewari', 'qwerty', 'k.debi.tewari@mondriaanict.nl', '31612345678', 'img/personen/kdebitewari.png', NULL, NULL, NULL, 5, 'leerling'),
(105, 'Roland', NULL, 'Dobbelaer', 'rdobbelaer', 'qwerty', 'r.dobbelaer@mondriaanict.nl', '31612345678', 'img/personen/rdobbelaer.png', NULL, NULL, NULL, 5, 'leerling'),
(106, 'Othman', NULL, 'El Hamami', 'oelhamami', 'qwerty', 'o.elhamami@mondriaanict.nl', '31612345678', 'img/personen/oelhamami.png', NULL, NULL, NULL, 5, 'leerling'),
(107, 'Gedion', NULL, 'Frijmersum', 'gfrijmersum', 'qwerty', 'g.frijmersum@mondriaanict.nl', '31612345678', 'img/personen/gfrijmersum.png', NULL, NULL, NULL, 5, 'leerling'),
(108, 'Shaquille', NULL, 'Ghazi', 'sghazi', 'qwerty', 's.ghazi@mondriaanict.nl', '31612345678', 'img/personen/sghazi.png', NULL, NULL, NULL, 5, 'leerling'),
(109, 'Alex', 'van', 'Hooijdonk', 'ahooijdonk', 'qwerty', 'a.van.hooijdonk@mondriaanict.nl', '31612345678', 'img/personen/ahooijdonk.png', NULL, NULL, NULL, 5, 'leerling'),
(110, 'Zakaria', NULL, 'Hsaïni', 'zhsaïni', 'qwerty', 'z.hsaïni@mondriaanict.nl', '31612345678', 'img/personen/zhsaïni.png', NULL, NULL, NULL, 5, 'leerling'),
(111, 'Ismail', NULL, 'Kayadelen', 'ikayadelen', 'qwerty', 'i.kayadelen@mondriaanict.nl', '31612345678', 'img/personen/ikayadelen.png', NULL, NULL, NULL, 5, 'leerling'),
(112, 'Furkan', NULL, 'Keskin', 'fkeskin', 'qwerty', 'f.keskin@mondriaanict.nl', '31612345678', 'img/personen/fkeskin.png', NULL, NULL, NULL, 5, 'leerling'),
(113, 'Maxime', NULL, 'Koomen', 'mkoomen', 'qwerty', 'm.koomen@mondriaanict.nl', '31612345678', 'img/personen/mkoomen.png', NULL, NULL, NULL, 5, 'leerling'),
(114, 'Stijn', NULL, 'Kulche', 'skulche', 'qwerty', 's.kulche@mondriaanict.nl', '31612345678', 'img/personen/skulche.png', NULL, NULL, NULL, 5, 'leerling'),
(115, 'Tolga', NULL, 'Mert', 'tmert', 'qwerty', 't.mert@mondriaanict.nl', '31612345678', 'img/personen/tmert.png', NULL, NULL, NULL, 5, 'leerling'),
(116, 'Luca', NULL, 'Mula', 'lmula', 'qwerty', 'l.mula@mondriaanict.nl', '31612345678', 'img/personen/lmula.png', NULL, NULL, NULL, 5, 'leerling'),
(117, 'Sjoerd', NULL, 'Olsthoorn', 'solsthoorn', 'qwerty', 's.olsthoorn@mondriaanict.nl', '31612345678', 'img/personen/solsthoorn.png', NULL, NULL, NULL, 5, 'leerling'),
(118, 'Luchiano', NULL, 'Ramkhelawan', 'lramkhelawan', 'qwerty', 'l.ramkhelawan@mondriaanict.nl', '31612345678', 'img/personen/lramkhelawan.png', NULL, NULL, NULL, 5, 'leerling'),
(119, 'Ian', NULL, 'Schön', 'ischön', 'qwerty', 'i.schön@mondriaanict.nl', '31612345678', 'img/personen/ischön.png', NULL, NULL, NULL, 5, 'leerling'),
(120, 'Saraï', NULL, 'Schuurman Hess', 'sschuurmanhess', 'qwerty', 's.schuurman.hess@mondriaanict.nl', '31612345678', 'img/personen/sschuurmanhess.png', NULL, NULL, NULL, 5, 'leerling'),
(121, 'Amaru', NULL, 'Signore', 'asignore', 'qwerty', 'a.signore@mondriaanict.nl', '31612345678', 'img/personen/asignore.png', NULL, NULL, NULL, 5, 'leerling'),
(122, 'Jasper', NULL, 'Veldhuizen', 'jveldhuizen', 'qwerty', 'j.veldhuizen@mondriaanict.nl', '31612345678', 'img/personen/jveldhuizen.png', NULL, NULL, NULL, 5, 'leerling'),
(123, 'Tim', NULL, 'Vlasblom', 'tvlasblom', 'qwerty', 't.vlasblom@mondriaanict.nl', '31612345678', 'img/personen/tvlasblom.png', NULL, NULL, NULL, 5, 'leerling'),
(124, 'Thijmen', NULL, 'Wittekoek', 'twittekoek', 'qwerty', 't.wittekoek@mondriaanict.nl', '31612345678', 'img/personen/twittekoek.png', NULL, NULL, NULL, 5, 'leerling'),
(125, 'Alex', NULL, 'Yordanov', 'ayordanov', 'qwerty', 'a.yordanov@mondriaanict.nl', '31612345678', 'img/personen/ayordanov.png', NULL, NULL, NULL, 5, 'leerling'),
(126, 'Sam', NULL, 'Cinjee', 'scinjee', 'qwerty', 's.cinjee@mondriaanict.nl', '31612345678', 'img/personen/scinjee.png', NULL, NULL, NULL, 6, 'leerling'),
(127, 'Iwan', NULL, 'Dimitrijevic', 'idimitrijevic', 'qwerty', 'i.dimitrijevic@mondriaanict.nl', '31612345678', 'img/personen/idimitrijevic.png', NULL, NULL, NULL, 6, 'leerling'),
(128, 'Alexander', NULL, 'Eijgermans', 'aeijgermans', 'qwerty', 'a.eijgermans@mondriaanict.nl', '31612345678', 'img/personen/aeijgermans.png', NULL, NULL, NULL, 6, 'leerling'),
(129, 'Yunus', NULL, 'Gögce', 'ygögce', 'qwerty', 'y.gögce@mondriaanict.nl', '31612345678', 'img/personen/ygögce.png', NULL, NULL, NULL, 6, 'leerling'),
(130, 'Geert', NULL, 'Heemskerk', 'gheemskerk', 'qwerty', 'g.heemskerk@mondriaanict.nl', '31612345678', 'img/personen/gheemskerk.png', NULL, NULL, NULL, 6, 'leerling'),
(131, 'Pim', 'van', 'Horssen', 'phorssen', 'qwerty', 'p.van.horssen@mondriaanict.nl', '31612345678', 'img/personen/phorssen.png', NULL, NULL, NULL, 6, 'leerling'),
(132, 'Jonathan', NULL, 'Kerkhoven', 'jkerkhoven', 'qwerty', 'j.kerkhoven@mondriaanict.nl', '31612345678', 'img/personen/jkerkhoven.png', NULL, NULL, NULL, 6, 'leerling'),
(133, 'Wouter', 'van', 'Kester', 'wkester', 'qwerty', 'w.van.kester@mondriaanict.nl', '31612345678', 'img/personen/wkester.png', NULL, NULL, NULL, 6, 'leerling'),
(134, 'Arjan', NULL, 'Kuiper', 'akuiper', 'qwerty', 'a.kuiper@mondriaanict.nl', '31612345678', 'img/personen/akuiper.png', NULL, NULL, NULL, 6, 'leerling'),
(135, 'Els', NULL, 'Lok', 'elok', 'qwerty', 'e.lok@mondriaanict.nl', '31612345678', 'img/personen/elok.png', NULL, NULL, NULL, 6, 'leerling'),
(136, 'Mike', NULL, 'Melein', 'mmelein', 'qwerty', 'm.melein@mondriaanict.nl', '31612345678', 'img/personen/mmelein.png', NULL, NULL, NULL, 6, 'leerling'),
(137, 'Sanjay', NULL, 'Ragunath', 'sragunath', 'qwerty', 's.ragunath@mondriaanict.nl', '31612345678', 'img/personen/sragunath.png', NULL, NULL, NULL, 6, 'leerling'),
(138, 'Cas', NULL, 'Vastenburg', 'cvastenburg', 'qwerty', 'c.vastenburg@mondriaanict.nl', '31612345678', 'img/personen/cvastenburg.png', NULL, NULL, NULL, 6, 'leerling'),
(139, 'Tim', 'van de', 'Ven', 'tven', 'qwerty', 't.van.de.ven@mondriaanict.nl', '31612345678', 'img/personen/tven.png', NULL, NULL, NULL, 6, 'leerling'),
(140, 'Casey', NULL, 'Vianen', 'cvianen', 'qwerty', 'c.vianen@mondriaanict.nl', '31612345678', 'img/personen/cvianen.png', NULL, NULL, NULL, 6, 'leerling'),
(141, 'Steven', NULL, 'Wu', 'swu', 'qwerty', 's.wu@mondriaanict.nl', '31612345678', 'img/personen/swu.png', NULL, NULL, NULL, 6, 'leerling'),
(142, 'Karim', NULL, 'Adelbaki', 'kadelbaki', 'qwerty', 'k.adelbaki@mondriaanict.nl', '31612345678', 'img/personen/kadelbaki.png', NULL, NULL, NULL, 7, 'leerling'),
(143, 'Jay', NULL, 'Amanh', 'jamanh', 'qwerty', 'j.amanh@mondriaanict.nl', '31612345678', 'img/personen/jamanh.png', NULL, NULL, NULL, 7, 'leerling'),
(144, 'Maciej', NULL, 'Antolak', 'mantolak', 'qwerty', 'm.antolak@mondriaanict.nl', '31612345678', 'img/personen/mantolak.png', NULL, NULL, NULL, 7, 'leerling'),
(145, 'Jason', 'van', 'Baardwijk', 'jbaardwijk', 'qwerty', 'j.van.baardwijk@mondriaanict.nl', '31612345678', 'img/personen/jbaardwijk.png', NULL, NULL, NULL, 7, 'leerling'),
(146, 'Ismael', 'Al', 'Bazi', 'ibazi', 'qwerty', 'i.al.bazi@mondriaanict.nl', '31612345678', 'img/personen/ibazi.png', NULL, NULL, NULL, 7, 'leerling'),
(147, 'Toni', NULL, 'Bergenhenegouwen', 'tbergenhenegouwen', 'qwerty', 't.bergenhenegouwen@mondriaanict.nl', '31612345678', 'img/personen/tbergenhenegouwen.png', NULL, NULL, NULL, 7, 'leerling'),
(148, 'Nick', NULL, 'Duijndam', 'nduijndam', 'qwerty', 'n.duijndam@mondriaanict.nl', '31612345678', 'img/personen/nduijndam.png', NULL, NULL, NULL, 7, 'leerling'),
(149, 'Alexander', 'van den', 'Ende', 'aende', 'qwerty', 'a.van.den.ende@mondriaanict.nl', '31612345678', 'img/personen/aende.png', NULL, NULL, NULL, 7, 'leerling'),
(150, 'Erik', NULL, 'Engelgeer', 'eengelgeer', 'qwerty', 'e.engelgeer@mondriaanict.nl', '31612345678', 'img/personen/eengelgeer.png', NULL, NULL, NULL, 7, 'leerling'),
(151, 'Carlo', 'van der', 'Haar', 'chaar', 'qwerty', 'c.van.der.haar@mondriaanict.nl', '31612345678', 'img/personen/chaar.png', NULL, NULL, NULL, 7, 'leerling'),
(152, 'Rodin', NULL, 'Jagga', 'rjagga', 'qwerty', 'r.jagga@mondriaanict.nl', '31612345678', 'img/personen/rjagga.png', NULL, NULL, NULL, 7, 'leerling'),
(153, 'Stefan', NULL, 'Janssen', 'sjanssen', 'qwerty', 's.janssen@mondriaanict.nl', '31612345678', 'img/personen/sjanssen.png', NULL, NULL, NULL, 7, 'leerling'),
(154, 'Nick', NULL, 'Keereweer', 'nkeereweer', 'qwerty', 'n.keereweer@mondriaanict.nl', '31612345678', 'img/personen/nkeereweer.png', NULL, NULL, NULL, 7, 'leerling'),
(155, 'Numan', NULL, 'Kuru', 'nkuru', 'qwerty', 'n.kuru@mondriaanict.nl', '31612345678', 'img/personen/nkuru.png', NULL, NULL, NULL, 7, 'leerling'),
(156, 'Joost', 'de', 'Niet', 'jniet', 'qwerty', 'j.de.niet@mondriaanict.nl', '31612345678', 'img/personen/jniet.png', NULL, NULL, NULL, 7, 'leerling'),
(157, 'Jeffrey', 'van', 'Oosterwijk', 'joosterwijk', 'qwerty', 'j.van.oosterwijk@mondriaanict.nl', '31612345678', 'img/personen/joosterwijk.png', NULL, NULL, NULL, 7, 'leerling'),
(158, 'Jeffrey', NULL, 'Remkes', 'jremkes', 'qwerty', 'j.remkes@mondriaanict.nl', '31612345678', 'img/personen/jremkes.png', NULL, NULL, NULL, 7, 'leerling'),
(159, 'Guido', NULL, 'Slootweg', 'gslootweg', 'qwerty', 'g.slootweg@mondriaanict.nl', '31612345678', 'img/personen/gslootweg.png', NULL, NULL, NULL, 7, 'leerling'),
(160, 'Stefan', NULL, 'Streur', 'sstreur', 'qwerty', 's.streur@mondriaanict.nl', '31612345678', 'img/personen/sstreur.png', NULL, NULL, NULL, 7, 'leerling'),
(161, 'Danny', NULL, 'Suijker', 'dsuijker', 'qwerty', 'd.suijker@mondriaanict.nl', '31612345678', 'img/personen/dsuijker.png', NULL, NULL, NULL, 7, 'leerling'),
(162, 'Soner', NULL, 'Tunc', 'stunc', 'qwerty', 's.tunc@mondriaanict.nl', '31612345678', 'img/personen/stunc.png', NULL, NULL, NULL, 7, 'leerling'),
(163, 'Paul', 'van de', 'Avendonk', 'pavendonk', 'qwerty', 'p.van.de.avendonk@mondriaanict.nl', '31612345678', 'img/personen/pavendonk.png', NULL, NULL, NULL, 8, 'leerling'),
(164, 'Tom', 'van der', 'Lugt', 'tlugt', 'qwerty', 't.van.der.lugt@mondriaanict.nl', '31612345678', 'img/personen/tlugt.png', NULL, NULL, NULL, 8, 'leerling'),
(165, 'Socrates', NULL, 'Coto Matey', 'scotomatey', 'qwerty', 's.coto.matey@mondriaanict.nl', '31612345678', 'img/personen/scotomatey.png', NULL, NULL, NULL, 9, 'leerling'),
(166, 'Dylan', NULL, 'Jarmohamed', 'djarmohamed', 'qwerty', 'd.jarmohamed@mondriaanict.nl', '31612345678', 'img/personen/djarmohamed.png', NULL, NULL, NULL, 9, 'leerling'),
(167, 'Nassiem', NULL, 'Lahmidi', 'nlahmidi', 'qwerty', 'n.lahmidi@mondriaanict.nl', '31612345678', 'img/personen/nlahmidi.png', NULL, NULL, NULL, 9, 'leerling'),
(168, 'Sibren', 'van', 'Paassen', 'spaassen', 'qwerty', 's.van.paassen@mondriaanict.nl', '31612345678', 'img/personen/spaassen.png', NULL, NULL, NULL, 9, 'leerling'),
(169, 'Taner', NULL, 'Sahin', 'tsahin', 'qwerty', 't.sahin@mondriaanict.nl', '31612345678', 'img/personen/tsahin.png', NULL, NULL, NULL, 9, 'leerling'),
(170, 'Lars', NULL, 'Aalbertsen', 'laalbertsen', 'qwerty', 'l.aalbertsen@mondriaanict.nl', '31612345678', 'img/personen/laalbertsen.png', 'asdasdasd', NULL, NULL, 10, 'leerling'),
(171, 'Adnan', NULL, 'Akbas', 'aakbas', 'qwerty', 'a.akbas@mondriaanict.nl', '31612345678', 'img/personen/aakbas.png', NULL, NULL, NULL, 10, 'leerling'),
(172, 'Boraida', NULL, 'Al-Assbahi', 'balassbahi', 'qwerty', 'b.alassbahi@mondriaanict.nl', '31612345678', 'img/personen/balassbahi.png', NULL, NULL, NULL, 10, 'leerling'),
(173, 'Jeffrey', 'van den', 'Bos', 'jbos', 'qwerty', 'j.van.den.bos@mondriaanict.nl', '31612345678', 'img/personen/jbos.png', NULL, NULL, NULL, 10, 'leerling'),
(174, 'Joey', 'de', 'Brabander', 'jbrabander', 'qwerty', 'j.de.brabander@mondriaanict.nl', '31612345678', 'img/personen/jbrabander.png', NULL, NULL, NULL, 10, 'leerling'),
(175, 'Teng', NULL, 'Chi', 'tchi', 'qwerty', 't.chi@mondriaanict.nl', '31612345678', 'img/personen/tchi.png', NULL, NULL, NULL, 10, 'leerling'),
(176, 'Ariyan', NULL, 'Efe', 'aefe', 'qwerty', 'a.efe@mondriaanict.nl', '31612345678', 'img/personen/aefe.png', NULL, NULL, NULL, 10, 'leerling'),
(177, 'Jacob', NULL, 'Farhaoui', 'jfarhaoui', 'qwerty', 'j.farhaoui@mondriaanict.nl', '31612345678', 'img/personen/jfarhaoui.png', NULL, NULL, NULL, 10, 'leerling'),
(178, 'Ian', NULL, 'Gerrebrands', 'igerrebrands', 'qwerty', 'i.gerrebrands@mondriaanict.nl', '31612345678', 'img/personen/igerrebrands.png', NULL, NULL, NULL, 10, 'leerling'),
(179, 'Nigel', NULL, 'Hoegee', 'nhoegee', 'qwerty', 'n.hoegee@mondriaanict.nl', '31612345678', 'img/personen/nhoegee.png', NULL, NULL, NULL, 10, 'leerling'),
(180, 'Max', 'van', 'Holstein', 'mholstein', 'qwerty', 'm.holstein@mondriaanict.nl', '31612345678', 'img/personen/mholstein.png', NULL, NULL, NULL, 10, 'leerling'),
(181, 'Ryan', NULL, 'Jainandan-Jha', 'rjainandanjha', 'qwerty', 'r.jainandanjha@mondriaanict.nl', '31612345678', 'img/personen/rjainandanjha.png', NULL, NULL, NULL, 10, 'leerling'),
(182, 'Sergio', NULL, 'Jozee', 'sjozee', 'qwerty', 's.jozee@mondriaanict.nl', '31612345678', 'img/personen/sjozee.png', NULL, NULL, NULL, 10, 'leerling'),
(183, 'Abdel', 'El', 'Kharbachi', 'aelkharbachi', 'qwerty', 'a.el.kharbachi@mondriaanict.nl', '31612345678', 'img/personen/aelkharbachi.png', NULL, NULL, NULL, 10, 'leerling'),
(184, 'Ruben', 'van der', 'Knaap', 'rknaap', 'qwerty', 'r.van.der.knaap@mondriaanict.nl', '31612345678', 'img/personen/rknaap.png', NULL, NULL, NULL, 10, 'leerling'),
(185, 'Oussama', NULL, 'Laghmouchi', 'olaghmouchi', 'qwerty', 'o.laghmouchi@mondriaanict.nl', '31612345678', 'img/personen/olaghmouchi.png', NULL, NULL, NULL, 10, 'leerling'),
(186, 'Jeffrey', NULL, 'Lo-A-Foe', 'jloafoe', 'qwerty', 'j.loafoe@mondriaanict.nl', '31612345678', 'img/personen/jloafoe.png', NULL, NULL, NULL, 10, 'leerling'),
(187, 'Michael', 'Sean', 'Netelenbos', 'mnetelenbos', 'qwerty', 'm.sean.netelenbos@mondriaanict.nl', '31612345678', 'img/personen/mnetelenbos.png', NULL, NULL, NULL, 10, 'leerling'),
(188, 'Ruchir', NULL, 'Ramlal', 'rramlal', 'qwerty', 'r.ramlal@mondriaanict.nl', '31612345678', 'img/personen/rramlal.png', NULL, NULL, NULL, 10, 'leerling'),
(189, 'Hugo', 'de', 'Ruiter', 'hruiter', 'qwerty', 'h.de.ruiter@mondriaanict.nl', '31612345678', 'img/personen/hruiter.png', NULL, NULL, NULL, 10, 'leerling'),
(190, 'Rickardo', NULL, 'Schokker', 'rschokker', 'qwerty', 'r.schokker@mondriaanict.nl', '31612345678', 'img/personen/rschokker.png', NULL, NULL, NULL, 10, 'leerling'),
(191, 'Nathan', NULL, 'Taal', 'ntaal', 'qwerty', 'n.taal@mondriaanict.nl', '31612345678', 'img/personen/ntaal.png', NULL, NULL, NULL, 10, 'leerling'),
(192, 'Zafer', NULL, 'Ulusal', 'zulusal', 'qwerty', 'z.ulusal@mondriaanict.nl', '31612345678', 'img/personen/zulusal.png', NULL, NULL, NULL, 10, 'leerling'),
(193, 'Nando', NULL, 'Veenendaal', 'nveenendaal', 'qwerty', 'n.veenendaal@mondriaanict.nl', '31612345678', 'img/personen/nveenendaal.png', NULL, NULL, NULL, 10, 'leerling'),
(194, 'Tjeerd', NULL, 'Verschragen', 'tverschragen', 'qwerty', 't.verschragen@mondriaanict.nl', '31612345678', 'img/personen/tverschragen.png', NULL, NULL, NULL, 10, 'leerling'),
(195, 'Julie', NULL, 'Vojczekhovskiy', 'jvojczekhovskiy', 'qwerty', 'j.vojczekhovskiy@mondriaanict.nl', '31612345678', 'img/personen/jvojczekhovskiy.png', NULL, NULL, NULL, 10, 'leerling'),
(196, 'Colin', NULL, 'Werkhoven', 'cwerkhoven', 'qwerty', 'c.werkhoven@mondriaanict.nl', '31612345678', 'img/personen/cwerkhoven.png', NULL, NULL, NULL, 10, 'leerling'),
(197, 'Vedat', NULL, 'Yilmaz', 'vyilmaz', 'qwerty', 'v.yilmaz@mondriaanict.nl', '31612345678', 'img/personen/vyilmaz.png', NULL, NULL, NULL, 10, 'leerling'),
(198, 'Quenten', NULL, 'Zandvliet', 'qzandvliet', 'qwerty', 'q.zandvliet@mondriaanict.nl', '31612345678', 'img/personen/qzandvliet.png', NULL, NULL, NULL, 10, 'leerling'),
(199, 'Mandy', 'van', 'Zetten', 'mzetten', 'qwerty', 'm.zetten@mondriaanict.nl', '31612345678', 'img/personen/mzetten.png', NULL, NULL, NULL, 10, 'leerling'),
(200, 'Lennard', NULL, 'Zevenbergen', 'lzevenbergen', 'qwerty', 'l.zevenbergen@mondriaanict.nl', '31612345678', 'img/personen/lzevenbergen.png', NULL, NULL, NULL, 11, 'leerling'),
(201, 'Robbin', 'den', 'Heijer', 'rheijer', 'qwerty', 'r.den.heijer@mondriaanict.nl', '31612345678', 'img/personen/rheijer.png', NULL, NULL, NULL, 11, 'leerling'),
(202, 'M', NULL, 'Kasar', 'mkasar', 'qwerty', 'm.kasar@mondriaanict.nl', '31612345678', 'img/personen/default.png', NULL, NULL, NULL, NULL, 'docent'),
(203, 'P', NULL, 'Nederpel', 'pnederpel', 'qwerty', 'p.nederpel@mondriaanict.nl', '31612345678', 'img/personen/default.png', NULL, NULL, NULL, NULL, 'docent'),
(204, 'W.A.M', 'van', 'Tol', 'wtol', 'qwerty', 'w.tol@mondriaanict.nl', '31612345678', 'img/personenen/wtol.png', NULL, NULL, NULL, NULL, 'docent'),
(205, 'R', NULL, 'Baouch', 'rbaouch', 'qwerty', 'r.baouch@mondriaanict.nl', '31612345678', 'img/personen/rbaouch.png', NULL, NULL, NULL, NULL, 'docent'),
(206, 'B.C.', 'van', 'Halem', 'bhalem', 'qwerty', 'b.van.halem@mondriaanict.nl', '31612345678', 'img/personen/bhalem.png', NULL, NULL, NULL, NULL, 'docent'),
(207, 'B.C.1', 'van1', 'Halem', 'bhalem1', 'qwerty', 'b.van.halem@mondriaanict.nl', '31612345678', 'img/personen/bhalem.png', NULL, NULL, NULL, NULL, 'docent'),
(208, 'B.C.2', 'van2', 'Halem', 'bhalem2', 'qwerty', 'b.van.halem@mondriaanict.nl', '31612345678', 'img/personen/bhalem.png', NULL, NULL, NULL, NULL, 'docent'),
(209, 'B.C.3', 'van3', 'Halem', 'bhalem3', 'qwerty', 'b.van.halem@mondriaanict.nl', '31612345678', 'img/personen/bhalem.png', NULL, NULL, NULL, NULL, 'docent'),
(210, 'B.C.4', 'van4', 'Halem', 'bhalem4', 'qwerty', 'b.van.halem@mondriaanict.nl', '31612345678', 'img/personen/bhalem.png', NULL, NULL, NULL, NULL, 'docent'),
(211, 'B.C.5', 'van5', 'Halem', 'bhalem5', 'qwerty', 'b.van.halem@mondriaanict.nl', '31612345678', 'img/personen/bhalem.png', NULL, NULL, NULL, NULL, 'docent'),
(212, 'B.C.6', 'van6', 'Halem', 'bhalem6', 'qwerty', 'b.van.halem@mondriaanict.nl', '31612345678', 'img/personen/bhalem.png', NULL, NULL, NULL, NULL, 'docent'),
(213, 'M', 'de', 'Kok', 'mkok', 'qwerty', 'm.de.kok@mondriaanict.nl', '31612345678', 'img/personen/mkok.jpg', NULL, NULL, NULL, NULL, 'directeur');


/*--- -Assign Teachers to Class- ---*/
UPDATE `klassen` 
SET `klassen`.`mentor_id` = 
CASE `klassen`.`id` 
    WHEN 1 THEN 202
    WHEN 2 THEN 203
    WHEN 3 THEN 204
    WHEN 4 THEN 205
    WHEN 5 THEN 206
    WHEN 6 THEN 207
    WHEN 7 THEN 208
    WHEN 8 THEN 209
    WHEN 9 THEN 210
    WHEN 10 THEN 211
    wHEN 11 THEN 212
END 
WHERE `klassen`.`id` IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11);